### ISSUE TITLE
Integrate updated data

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/contactdata#1]
https://doi.org/10.1101/2020.07.22.20159772

**Comment by BlackEdder** [comment]
Any progress on this?

**Comment by Bisaloo** [comment]
Not really because I wasn't sure there was interest but if that's something that would be useful to you, I can bump it on the priority list.

**Comment by BlackEdder** [comment]
It would definitely be useful for me, but only if it would be done over the next two week. Otherwise I'll probably just use the current values.

edit: So would be great if you have the time, but understand if you don't, and then I'll happily use the current values.

**Comment by Bisaloo** [comment]
Note to myself: adding the updated data also requires some interface changes.

- new argument to select data source: 2017 or 2020
- new argument to select urban vs rural vs all

**Comment by Bisaloo** [comment]
https://github.com/kieshaprem/synthetic-contact-matrices/tree/master/output/syntheticmatrices

**Comment by BlackEdder** [comment]
Thanks! It is not completely clear to me what their orientation is (e.g. age_to and age_from), but I guess I should be able to figure that out by comparing to some of the figures
